language: node_js
node_js:
  - '8'

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn size

after_success:
  - yarn coveralls

deploy:
  provider: npm
  skip_cleanup: true
  email: icrosil@gmail.com
  api_key:
    secure: ajnh6keIVPCrZ3an1aUxCFr0X3Fh50O73l4X2Rr8SQfLa2AML+1uorla9njiy2QjrtXm7kvWL7SW28+vl7kjwj5xuUoMv8szZscCVNOq+x8gYyY7RshWS261+HJaQ/vbpse5B0DNM1AQePIy8Qlnbn/H6Dgg/pEdnSmQ+QR9+35NjjGnEfdIKeJ6yqRPWcJZjdmrUxkOUOCmLzCNTOo6WZC1pwPGp/4CuFy+FKpBzHGTcbYckY52a6PJ3stt4I7A3Ib+A7Qygc2G9tL3aLFUK27tmxuYSP3P3n1TACP14JL+nDwfsUCyvKWKte8PYkLRkyic0zR5GRmZM14KEFQTnrcQphcGOghnxurX372Nz+dcxW1L3zgPXQi/HN8INC0UV1QVmql47DCCPttfs0TC9gkwjk7Lgv523e1k21qXuhbEP2HSmsFTNFWWnz5AAm6xc4/TDf8cfofRo8rfW0+43l65aqA1SZK+DOVO/nTNk2bT4XLKn5LgkX6kPbuOKUHhD++qCUItpcaFynl9gZh6xpQ9TzOnCTUTS0hgRfPt8ldmvLpKFaz9qwBB7KAIwAvRG5KyDFjY29/3KrAWiB558FlvKZrw1ekOsKpG8a6CYiHemkuhZ/z4UXOo9iJCurfZ7kfwdgRgOfzy0gPPvmRlkuxIi7cwatw5HHqQI2vqZGY=
  on:
    node: '8'
    repo: icrosil/remob
    all_branches: true

notifications:
  email:
    recipients:
      - icrosil@gmail.com
    on_success: change
    on_failure: always
