language: node_js
node_js:
- '10'
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn deps
- yarn lint
- yarn test:ci
- yarn build
- yarn size
after_success:
- yarn coveralls
deploy:
  provider: npm
  skip_cleanup: true
  email: icrosil@gmail.com
  api_key:
    secure: KrMSvRSUA4QlUufs0HxhE5VTtQCe8TN8Xt2+7nkuQcaP632KGjqQDKlvdw0YhiTJHtrZltCINhraXyyMz6qEdAIvBAZTpRRcpenyKs3CpdQrDEdtW1fIw60gKvuizNP6LdRDI99tpEau5gObHKHPGeRWhgaFVP/yTUBPA7I4fajQvpP09gyoWYxRhnz86Al9eLIH9nSZWXivOA6ZxDQOW32c7woEh64h49QY2YecAsmQGk+HW/AIrGOGYTs7pRfzBc3NTgrjdvdowCFA9G+2BqJsGELmRpAfOUnnx5Yzo3xtvtqUD+AFCB45/a3sdnSf4rvjqBDM80vMTuIxAepwJAW4V37umf9kuZoTy4UGZwYABdxpRKgXd1gQ5RRE00OVWsQFbL4GDzwhf/nOryBpYRQAkHj39kLV/NswpnhiQ0dZUJSrUis/1GSMDwAPi6jWhphsPMB9blwJp6TvW0ammbcBgjYAuxNjOlSZOMDOZ/HpJGrAiy/n1n5PazEduyBRGhqACbSA5ZrXtQh0UQ5uBldevAAzkVpdn7rbc8yX9ML5lVOJ7cWF1ozTdQkVp+1AMKLzE2dlMrl4zaXyRmDDbrGjsXAlSsZb48S6Ay3t1dVHAU3iGHfy35G57EF+wpN5mO3Ym5vdTM3WY7FfcMkyUJCMUg3BFH7AUvOEqe0MAjM=
  on:
    node: '10'
    repo: icrosil/remob
    all_branches: true
notifications:
  email:
    recipients:
    - icrosil@gmail.com
    on_success: change
    on_failure: always
