language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn deps
- yarn lint
- yarn test:ci
- yarn build
- yarn size
after_success:
- yarn coveralls
deploy:
  provider: npm
  skip_cleanup: true
  email: icrosil@gmail.com
  api_key:
    secure: dypZIcKkdlUwC5wmBQOCZuyxF5VwpjpZdyK3BfRTW3lbjkMxJui3MBwXbvacD9eG2cLkagrhUuNcxO5EuZWm+gMdhzGUYyN65OPajOPXFmWeUUEGVrRExpq6m3IGwc5eFfh64IWs+7pBuoUsfY+Tsz6ybwxx0SPV0Q6gdeb37XyjMWWHDOKzgdW6nfGUnKV2I9dDa5uQrlq/wppkEmnGoc5ILeiEXOSSz0CeW1A+wt1Qh5vy2B1suPSFh1XZDNXvne+Anafi5Z+sq2GQ4NRcCwlqqJ9seG+XB0/R0u+rxz0ESCACeGazd5PArBNWiA8k3UR89+ZY9zc6BNfgRKF9YIY6MiWSL/exHqWP6kw3Y9llhgVUjdmAw3V4eO8ywFU8W/omdPYidupcKrgbQq7cjzloTjkKUTFEw9QxvXnE2wSI2QofL53eOAVj1ymHFsg1OthA3lWhqwgQzduPjc4+VSPTu6ZfZL6N3b4aPXrDfktyTi5D2Qt5ilK7tIyqtBHhnkMhF+MmeV5xujp5RVPE1HFkKRoWPRqyO94VyHG6P22O6T98hXB7in6bis51i4CEoo/7GBq3lrJN5gtid1lARo87W8qWiQEaWyncNdUEwJKWtoVZDBSTzBIhcLRzokDtbWsytChjJvdt0u2L7Mh5zC3r2Hk2Uy9kWHwroKTHlFM=
  on:
    node: '8'
    repo: icrosil/remob
    all_branches: true
notifications:
  email:
    recipients:
    - icrosil@gmail.com
    on_success: change
    on_failure: always
